services:
  api:
    image: ${DOCKER_REGISTRY-}doingtasks.api
    container_name: DoingTasks.Api
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    depends_on:
      - db

  web:
    image: ${DOCKER_REGISTRY-}doingtasks.web
    container_name: DoingTasks.Web
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

  db:
    image: postgres:16-alpine
    container_name: DoingTasks.Db
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db_doingtasks"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Strong_password_123!"