services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  web:
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/frontend/Angular/doing-tasks:/app
      - /app/node_modules

  db:
    environment:
      - POSTGRES_PASSWORD=Dev@Password123